import React, { useState } from 'react';
import html2canvas from 'html2canvas';
import { Eye, Printer, Download, Share2, Copy, MessageCircle } from 'lucide-react';
import type { BondInterestResponse } from '../../core/bondInterestApi';
import { useTranslation } from 'react-i18next';

interface Props {
  result: BondInterestResponse;
  onPreview: () => void;
}

const fmtDate = (d: string) =>
  new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

const fmtINR = (v: number) =>
  new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(v);

const durationStr = (r: BondInterestResponse) => {
  const parts: string[] = [];
  if (r.duration_years > 0) parts.push(`${r.duration_years}Y`);
  if (r.duration_months > 0) parts.push(`${r.duration_months}M`);
  if (r.duration_days > 0) parts.push(`${r.duration_days}D`);
  return parts.join(' ') || '0D';
};

export const BondStatementActions: React.FC<Props> = ({ result, onPreview }) => {
  const { t } = useTranslation(['bondCalculator']);

  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);

  const captureCanvas = async () => {
    const el = document.getElementById('bond-statement-capture-area');
    if (!el) throw new Error('Statement element not found');
    return html2canvas(el, {
      scale: 2,
      backgroundColor: '#ffffff',
      logging: false,
      useCORS: true,
      width: el.scrollWidth,
      height: el.scrollHeight,
    });
  };

  const handleDownloadImage = async () => {
    setBusy(true);
    try {
      const canvas = await captureCanvas();
      canvas.toBlob((blob) => {
        if (!blob) return;
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Bond_Statement_${fmtDate(result.bond_start_date).replace(/ /g, '-')}.png`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }, 'image/png');
    } catch (e) {
      alert('Failed to generate image.');
    } finally {
      setBusy(false);
    }
  };

  const handleShareImage = async () => {
    setBusy(true);
    try {
      const canvas = await captureCanvas();
      canvas.toBlob(async (blob) => {
        if (!blob) return;
        const file = new File([blob], 'Bond_Statement.png', { type: 'image/png' });
        if (navigator.share && navigator.canShare?.({ files: [file] })) {
          await navigator.share({ title: 'Bond Interest Statement', files: [file] });
        } else {
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = file.name;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(url);
        }
      }, 'image/png');
    } catch (e) {
      console.error(e);
    } finally {
      setBusy(false);
    }
  };

  const handlePrint = () => {
    const el = document.getElementById('bond-statement-capture-area');
    if (!el) return;
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`<html><head><title>Bond Statement</title><style>body{margin:0;display:flex;justify-content:center;}@media print{body{margin:0;}}</style></head><body>${el.outerHTML}</body></html>`);
    w.document.close();
    w.focus();
    setTimeout(() => { w.print(); w.close(); }, 300);
  };

  const whatsappText = () => {
    const lines = [
      '--------------------------------',
      '*Bond Interest Statement*',
      '',
      `Principal: ${fmtINR(result.principal)}`,
      `Interest Rate: ₹${result.interest_rate} per ₹100/month`,
      `Bond Date: ${fmtDate(result.bond_start_date)}`,
      `Calc Date: ${fmtDate(result.calculation_date)}`,
      `Duration: ${durationStr(result)}`,
      `Interest: ${fmtINR(result.interest)}`,
      `Total Amount: ${fmtINR(result.total_amount)}`,
      `Status: ${result.bond_status}`,
      '',
      result.suggested_new_principal
        ? `Suggested New Principal: ${fmtINR(result.suggested_new_principal)}`
        : null,
      '',
      '_Generated by ChitMate_',
      '--------------------------------',
    ].filter((l) => l !== null);
    return lines.join('\n');
  };

  const handleWhatsApp = () => {
    window.open(`https://wa.me/?text=${encodeURIComponent(whatsappText())}`, '_blank');
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(whatsappText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const btnBase =
    'flex items-center justify-center gap-2 py-3 px-4 rounded-xl font-semibold text-sm transition-all active:scale-95';

  return (
    <div className="w-full grid grid-cols-3 gap-2 mt-3">
      <button onClick={onPreview} className={`${btnBase} col-span-3 bg-purple-600 hover:bg-purple-700 text-white shadow-md shadow-purple-200`}>
        <Eye size={18} /> Preview Statement
      </button>

      <button onClick={handlePrint} className={`${btnBase} bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-50`}>
        <Printer size={16} />{t('bondCalculator:calculator_print')}</button>

      <button onClick={handleDownloadImage} disabled={busy} className={`${btnBase} bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-50 disabled:opacity-50`}>
        <Download size={16} /> {busy ? '...' : 'Image'}
      </button>

      <button onClick={handleShareImage} disabled={busy} className={`${btnBase} bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-200 hover:bg-gray-50 disabled:opacity-50`}>
        <Share2 size={16} />{t('bondCalculator:calculator_share')}</button>

      <button onClick={handleWhatsApp} className={`${btnBase} col-span-2 bg-[#25D366] hover:bg-[#1ebe5d] text-white shadow-md shadow-green-200`}>
        <MessageCircle size={16} /> WhatsApp
      </button>

      <button onClick={handleCopy} className={`${btnBase} ${copied ? 'bg-green-100 text-green-700 border-green-300' : 'bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-200'}`}>
        <Copy size={16} /> {copied ? 'Copied!' : 'Copy'}
      </button>
    </div>
  );
};
