"""phase 1 auth and organizer onboarding

Revision ID: 124c255733b3
Revises: 8f468229d192
Create Date: 2026-06-24 20:18:56.376665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '124c255733b3'
down_revision: Union[str, None] = '8f468229d192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('login_at', sa.DateTime(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('logout_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_table('members')
    op.add_column('organizers', sa.Column('organizer_code', sa.String(length=20), nullable=False))
    op.add_column('organizers', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('organizers', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('organizers', sa.Column('village', sa.String(length=100), nullable=True))
    op.add_column('organizers', sa.Column('mandal', sa.String(length=100), nullable=True))
    op.add_column('organizers', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('organizers', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizers', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('organizers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('organizers', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.drop_constraint(op.f('organizers_user_id_key'), 'organizers', type_='unique')
    op.create_unique_constraint(None, 'organizers', ['mobile'])
    op.create_unique_constraint(None, 'organizers', ['email'])
    op.create_unique_constraint(None, 'organizers', ['organizer_code'])
    op.drop_constraint(op.f('organizers_user_id_fkey'), 'organizers', type_='foreignkey')
    op.drop_column('organizers', 'user_id')
    op.add_column('users', sa.Column('organizer_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('member_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'organizers', ['organizer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'otp_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'member_id')
    op.drop_column('users', 'organizer_id')
    op.add_column('organizers', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('organizers_user_id_fkey'), 'organizers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organizers', type_='unique')
    op.drop_constraint(None, 'organizers', type_='unique')
    op.drop_constraint(None, 'organizers', type_='unique')
    op.create_unique_constraint(op.f('organizers_user_id_key'), 'organizers', ['user_id'])
    op.alter_column('organizers', 'name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('organizers', 'is_active')
    op.drop_column('organizers', 'pincode')
    op.drop_column('organizers', 'state')
    op.drop_column('organizers', 'district')
    op.drop_column('organizers', 'mandal')
    op.drop_column('organizers', 'village')
    op.drop_column('organizers', 'address')
    op.drop_column('organizers', 'email')
    op.drop_column('organizers', 'organizer_code')
    op.create_table('members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('members_created_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('members_deleted_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('members_updated_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('members_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('members_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('members_user_id_key'))
    )
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.drop_table('user_sessions')
    op.drop_table('login_audit_logs')
    # ### end Alembic commands ###
