"""phase_6_1_winner_payout_receipt

Revision ID: 4f93d75a26e8
Revises: f3345e2e21d3
Create Date: 2026-06-25 21:15:12.232492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f93d75a26e8'
down_revision: Union[str, None] = 'f3345e2e21d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chit_winner_payout_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('winner_payout_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_payout_id'], ['chit_winner_payouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chit_winner_payout_activity_logs_action_type'), 'chit_winner_payout_activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_chit_winner_payout_activity_logs_created_at'), 'chit_winner_payout_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_chit_winner_payout_activity_logs_organizer_id'), 'chit_winner_payout_activity_logs', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_chit_winner_payout_activity_logs_winner_payout_id'), 'chit_winner_payout_activity_logs', ['winner_payout_id'], unique=False)
    op.add_column('chit_winner_payouts', sa.Column('proof_file_url', sa.Text(), nullable=True))
    op.add_column('chit_winner_payouts', sa.Column('receipt_html_url', sa.Text(), nullable=True))
    op.add_column('chit_winner_payouts', sa.Column('receipt_image_url', sa.Text(), nullable=True))
    op.add_column('chit_winner_payouts', sa.Column('winner_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('chit_winner_payouts', sa.Column('winner_confirmation_note', sa.Text(), nullable=True))
    op.alter_column('chit_winner_payouts', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chit_winner_payouts', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('chit_winner_payouts', 'winner_confirmation_note')
    op.drop_column('chit_winner_payouts', 'winner_confirmed_at')
    op.drop_column('chit_winner_payouts', 'receipt_image_url')
    op.drop_column('chit_winner_payouts', 'receipt_html_url')
    op.drop_column('chit_winner_payouts', 'proof_file_url')
    op.drop_index(op.f('ix_chit_winner_payout_activity_logs_winner_payout_id'), table_name='chit_winner_payout_activity_logs')
    op.drop_index(op.f('ix_chit_winner_payout_activity_logs_organizer_id'), table_name='chit_winner_payout_activity_logs')
    op.drop_index(op.f('ix_chit_winner_payout_activity_logs_created_at'), table_name='chit_winner_payout_activity_logs')
    op.drop_index(op.f('ix_chit_winner_payout_activity_logs_action_type'), table_name='chit_winner_payout_activity_logs')
    op.drop_table('chit_winner_payout_activity_logs')
    # ### end Alembic commands ###
