"""phase 3 chit group management

Revision ID: 7930155d9176
Revises: cb627d45d902
Create Date: 2026-06-24 22:49:20.995594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7930155d9176'
down_revision: Union[str, None] = 'cb627d45d902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chit_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('chit_code', sa.String(length=50), nullable=False),
    sa.Column('chit_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_chit_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_installment_per_share', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('maintenance_charge', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('maintenance_charge_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('installment_due_day', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('allocated_shares', sa.Integer(), nullable=False),
    sa.Column('available_shares', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizer_id', 'chit_code', name='uq_chit_groups_organizer_chit_code'),
    sa.CheckConstraint('total_chit_value > 0', name='chk_chit_groups_total_chit_value'),
    sa.CheckConstraint('monthly_installment_per_share > 0', name='chk_chit_groups_monthly_installment'),
    sa.CheckConstraint('total_shares > 0', name='chk_chit_groups_total_shares'),
    sa.CheckConstraint('duration_months > 0', name='chk_chit_groups_duration_months'),
    sa.CheckConstraint('allocated_shares >= 0', name='chk_chit_groups_allocated_shares'),
    sa.CheckConstraint('available_shares >= 0', name='chk_chit_groups_available_shares'),
    sa.CheckConstraint('allocated_shares + available_shares = total_shares', name='chk_chit_groups_shares_sum'),
    sa.CheckConstraint('installment_due_day >= 1 AND installment_due_day <= 28', name='chk_chit_groups_installment_due_day')
    )
    op.create_index(op.f('ix_chit_groups_organizer_id'), 'chit_groups', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_chit_groups_start_date'), 'chit_groups', ['start_date'], unique=False)
    op.create_index(op.f('ix_chit_groups_status'), 'chit_groups', ['status'], unique=False)
    op.create_index('uq_chit_groups_organizer_name', 'chit_groups', ['organizer_id', 'chit_name'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('chit_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('chit_group_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('share_count > 0', name='chk_chit_memberships_share_count')
    )
    op.create_index(op.f('ix_chit_memberships_chit_group_id'), 'chit_memberships', ['chit_group_id'], unique=False)
    op.create_index(op.f('ix_chit_memberships_member_id'), 'chit_memberships', ['member_id'], unique=False)
    op.create_index(op.f('ix_chit_memberships_organizer_id'), 'chit_memberships', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_chit_memberships_status'), 'chit_memberships', ['status'], unique=False)
    op.create_index('uq_chit_memberships_group_member', 'chit_memberships', ['chit_group_id', 'member_id'], unique=True, postgresql_where='is_deleted = false')
    op.create_table('chit_group_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('chit_group_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['chit_memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chit_group_activity_logs_action_type'), 'chit_group_activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_chit_group_activity_logs_chit_group_id'), 'chit_group_activity_logs', ['chit_group_id'], unique=False)
    op.create_index(op.f('ix_chit_group_activity_logs_created_at'), 'chit_group_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_chit_group_activity_logs_membership_id'), 'chit_group_activity_logs', ['membership_id'], unique=False)
    op.create_index(op.f('ix_chit_group_activity_logs_organizer_id'), 'chit_group_activity_logs', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chit_group_activity_logs_organizer_id'), table_name='chit_group_activity_logs')
    op.drop_index(op.f('ix_chit_group_activity_logs_membership_id'), table_name='chit_group_activity_logs')
    op.drop_index(op.f('ix_chit_group_activity_logs_created_at'), table_name='chit_group_activity_logs')
    op.drop_index(op.f('ix_chit_group_activity_logs_chit_group_id'), table_name='chit_group_activity_logs')
    op.drop_index(op.f('ix_chit_group_activity_logs_action_type'), table_name='chit_group_activity_logs')
    op.drop_table('chit_group_activity_logs')
    op.drop_index('uq_chit_memberships_group_member', table_name='chit_memberships', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_chit_memberships_status'), table_name='chit_memberships')
    op.drop_index(op.f('ix_chit_memberships_organizer_id'), table_name='chit_memberships')
    op.drop_index(op.f('ix_chit_memberships_member_id'), table_name='chit_memberships')
    op.drop_index(op.f('ix_chit_memberships_chit_group_id'), table_name='chit_memberships')
    op.drop_table('chit_memberships')
    op.drop_index('uq_chit_groups_organizer_name', table_name='chit_groups', postgresql_where='is_deleted = false')
    op.drop_index(op.f('ix_chit_groups_status'), table_name='chit_groups')
    op.drop_index(op.f('ix_chit_groups_start_date'), table_name='chit_groups')
    op.drop_index(op.f('ix_chit_groups_organizer_id'), table_name='chit_groups')
    op.drop_table('chit_groups')
    # ### end Alembic commands ###
