"""Add otp_requests table

Revision ID: 97c44b23f3b3
Revises: e603a21aacc0
Create Date: 2026-07-11 16:29:56.675202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c44b23f3b3'
down_revision: Union[str, None] = 'e603a21aacc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_requests_mobile'), 'otp_requests', ['mobile'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_requests_mobile'), table_name='otp_requests')
    op.drop_table('otp_requests')
    # ### end Alembic commands ###
