"""add_password_hash_and_migrate

Revision ID: a9d8410355ff
Revises: d7e19ea141ec
Create Date: 2026-07-18 23:13:15.109374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d8410355ff'
down_revision: Union[str, None] = 'd7e19ea141ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from src.shared.common.helpers.password_helper import hash_password

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_requests_mobile'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.add_column('members', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Backfill default passwords as the hashed mobile number
    bind = op.get_bind()
    
    # Members
    members = bind.execute(sa.text('SELECT id, mobile FROM members')).fetchall()
    for member in members:
        member_id = member[0]
        mobile = member[1]
        if mobile:
            hashed_pwd = hash_password(mobile)
            bind.execute(
                sa.text('UPDATE members SET password_hash = :pwd WHERE id = :id'),
                {'pwd': hashed_pwd, 'id': member_id}
            )
            
    # Users
    users = bind.execute(sa.text('SELECT id, mobile FROM users')).fetchall()
    for user in users:
        user_id = user[0]
        mobile = user[1]
        if mobile:
            hashed_pwd = hash_password(mobile)
            bind.execute(
                sa.text('UPDATE users SET password_hash = :pwd WHERE id = :id'),
                {'pwd': hashed_pwd, 'id': user_id}
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('members', 'password_hash')
    op.create_table('otp_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('otp_requests_pkey'))
    )
    op.create_index(op.f('ix_otp_requests_mobile'), 'otp_requests', ['mobile'], unique=False)
    # ### end Alembic commands ###
