"""add collections and receipts tables

Revision ID: bb9536e43d6f
Revises: a1b2c3d4e5f6
Create Date: 2026-06-25 11:22:04.066843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9536e43d6f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_receipt_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=20), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizer_id', 'receipt_prefix', name='uq_receipt_sequences_organizer_prefix')
    )
    op.create_index(op.f('ix_payment_receipt_sequences_organizer_id'), 'payment_receipt_sequences', ['organizer_id'], unique=False)
    op.create_table('chit_payment_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('chit_group_id', sa.UUID(), nullable=False),
    sa.Column('chit_auction_id', sa.UUID(), nullable=False),
    sa.Column('monthly_member_due_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('collected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reversal_receipt_id', sa.UUID(), nullable=True),
    sa.Column('client_request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chit_auction_id'], ['chit_auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['chit_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monthly_member_due_id'], ['monthly_member_dues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversal_receipt_id'], ['chit_payment_receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizer_id', 'receipt_number', name='uq_payment_receipts_organizer_receipt_number')
    )
    op.create_index('idx_payment_receipts_client_request_id', 'chit_payment_receipts', ['organizer_id', 'client_request_id'], unique=True, postgresql_where='client_request_id IS NOT NULL')
    op.create_index(op.f('ix_chit_payment_receipts_chit_auction_id'), 'chit_payment_receipts', ['chit_auction_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_chit_group_id'), 'chit_payment_receipts', ['chit_group_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_client_request_id'), 'chit_payment_receipts', ['client_request_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_member_id'), 'chit_payment_receipts', ['member_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_membership_id'), 'chit_payment_receipts', ['membership_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_monthly_member_due_id'), 'chit_payment_receipts', ['monthly_member_due_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_organizer_id'), 'chit_payment_receipts', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_status'), 'chit_payment_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_payment_date'), 'chit_payment_receipts', ['payment_date'], unique=False)
    op.create_index(op.f('ix_chit_auction_bids_chit_group_id'), 'chit_auction_bids', ['chit_group_id'], unique=False)
    op.create_index(op.f('ix_chit_auction_bids_member_id'), 'chit_auction_bids', ['member_id'], unique=False)
    op.add_column('monthly_member_dues', sa.Column('total_paid_amount', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('monthly_member_dues', sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('monthly_member_dues', sa.Column('grace_period_end_date', sa.Date(), nullable=True))
    op.add_column('monthly_member_dues', sa.Column('last_payment_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_monthly_member_dues_member_id'), 'monthly_member_dues', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_member_dues_member_id'), table_name='monthly_member_dues')
    op.drop_column('monthly_member_dues', 'last_payment_at')
    op.drop_column('monthly_member_dues', 'grace_period_end_date')
    op.drop_column('monthly_member_dues', 'remaining_amount')
    op.drop_column('monthly_member_dues', 'total_paid_amount')
    op.drop_index(op.f('ix_chit_auction_bids_member_id'), table_name='chit_auction_bids')
    op.drop_index(op.f('ix_chit_auction_bids_chit_group_id'), table_name='chit_auction_bids')
    op.drop_index(op.f('ix_chit_payment_receipts_status'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_organizer_id'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_payment_date'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_monthly_member_due_id'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_membership_id'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_member_id'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_client_request_id'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_chit_group_id'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_payment_receipts_chit_auction_id'), table_name='chit_payment_receipts')
    op.drop_index('idx_payment_receipts_client_request_id', table_name='chit_payment_receipts', postgresql_where='client_request_id IS NOT NULL')
    op.drop_table('chit_payment_receipts')
    op.drop_index(op.f('ix_payment_receipt_sequences_organizer_id'), table_name='payment_receipt_sequences')
    op.drop_table('payment_receipt_sequences')
    # ### end Alembic commands ###
