"""phase 2 member management

Revision ID: cb627d45d902
Revises: 124c255733b3
Create Date: 2026-06-24 22:20:00.897535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb627d45d902'
down_revision: Union[str, None] = '124c255733b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('member_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('mandal', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('aadhaar_last4', sa.String(length=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organizer_id', 'member_code', name='uq_members_organizer_member_code'),
    sa.UniqueConstraint('organizer_id', 'mobile', name='uq_members_organizer_mobile')
    )
    op.create_index(op.f('ix_members_full_name'), 'members', ['full_name'], unique=False)
    op.create_index(op.f('ix_members_is_active'), 'members', ['is_active'], unique=False)
    op.create_index(op.f('ix_members_mobile'), 'members', ['mobile'], unique=False)
    op.create_index(op.f('ix_members_organizer_id'), 'members', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_members_village'), 'members', ['village'], unique=False)
    op.create_table('member_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_activity_logs_created_at'), 'member_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_member_activity_logs_member_id'), 'member_activity_logs', ['member_id'], unique=False)
    op.create_index(op.f('ix_member_activity_logs_organizer_id'), 'member_activity_logs', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_activity_logs_organizer_id'), table_name='member_activity_logs')
    op.drop_index(op.f('ix_member_activity_logs_member_id'), table_name='member_activity_logs')
    op.drop_index(op.f('ix_member_activity_logs_created_at'), table_name='member_activity_logs')
    op.drop_table('member_activity_logs')
    op.drop_index(op.f('ix_members_village'), table_name='members')
    op.drop_index(op.f('ix_members_organizer_id'), table_name='members')
    op.drop_index(op.f('ix_members_mobile'), table_name='members')
    op.drop_index(op.f('ix_members_is_active'), table_name='members')
    op.drop_index(op.f('ix_members_full_name'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
