"""Drop must_change_password from users

Revision ID: d7e19ea141ec
Revises: 213b5ccc4ae3
Create Date: 2026-07-12 22:34:54.087508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e19ea141ec'
down_revision: Union[str, None] = '213b5ccc4ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
