"""Add password_hash to Member

Revision ID: e603a21aacc0
Revises: 9d8d79aa03aa
Create Date: 2026-07-03 19:10:49.060273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e603a21aacc0'
down_revision: Union[str, None] = '9d8d79aa03aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chit_auctions_auction_date'), 'chit_auctions', ['auction_date'], unique=False)
    op.create_index(op.f('ix_chit_payment_receipts_payment_date'), 'chit_payment_receipts', ['payment_date'], unique=False)
    op.add_column('members', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_monthly_member_dues_due_date'), 'monthly_member_dues', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_member_dues_due_date'), table_name='monthly_member_dues')
    op.drop_column('members', 'password_hash')
    op.drop_index(op.f('ix_chit_payment_receipts_payment_date'), table_name='chit_payment_receipts')
    op.drop_index(op.f('ix_chit_auctions_auction_date'), table_name='chit_auctions')
    # ### end Alembic commands ###
