"""Add ChitWinnerPayout and ChitMonthFinancialClosure

Revision ID: f3345e2e21d3
Revises: f1e2d3c4b5a6
Create Date: 2026-06-25 18:55:51.027076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3345e2e21d3'
down_revision: Union[str, None] = 'f1e2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chit_month_financial_closures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('chit_group_id', sa.UUID(), nullable=False),
    sa.Column('chit_auction_id', sa.UUID(), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('active_member_count', sa.Integer(), nullable=False),
    sa.Column('gross_chit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('winning_bid_discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('maintenance_charge_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dividend_pool_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('dividend_per_share', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_collection_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_collection_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pending_collection_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('winner_payout_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('organizer_contribution_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_cash_position', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('shortfall_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('surplus_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closure_status', sa.String(length=30), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chit_auction_id'], ['chit_auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chit_group_id', 'month_number', name='uq_financial_closures_group_month')
    )
    op.create_index(op.f('ix_chit_month_financial_closures_chit_auction_id'), 'chit_month_financial_closures', ['chit_auction_id'], unique=False)
    op.create_index(op.f('ix_chit_month_financial_closures_chit_group_id'), 'chit_month_financial_closures', ['chit_group_id'], unique=False)
    op.create_index(op.f('ix_chit_month_financial_closures_closure_status'), 'chit_month_financial_closures', ['closure_status'], unique=False)
    op.create_index(op.f('ix_chit_month_financial_closures_organizer_id'), 'chit_month_financial_closures', ['organizer_id'], unique=False)
    op.create_table('chit_winner_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('chit_group_id', sa.UUID(), nullable=False),
    sa.Column('chit_auction_id', sa.UUID(), nullable=False),
    sa.Column('winner_membership_id', sa.UUID(), nullable=False),
    sa.Column('winner_member_id', sa.UUID(), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('gross_chit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('winning_bid_discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('maintenance_charge_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payout_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collection_expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collection_received_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('collection_pending_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('organizer_contribution_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payout_source', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payout_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('payout_receipt_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reversal_payout_id', sa.UUID(), nullable=True),
    sa.Column('client_request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chit_auction_id'], ['chit_auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chit_group_id'], ['chit_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversal_payout_id'], ['chit_winner_payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_membership_id'], ['chit_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chit_group_id', 'month_number', name='uq_winner_payouts_group_month'),
    sa.UniqueConstraint('organizer_id', 'payout_receipt_number', name='uq_winner_payouts_organizer_receipt')
    )
    op.create_index('idx_winner_payouts_client_request_id', 'chit_winner_payouts', ['organizer_id', 'client_request_id'], unique=True, postgresql_where='client_request_id IS NOT NULL')
    op.create_index(op.f('ix_chit_winner_payouts_chit_auction_id'), 'chit_winner_payouts', ['chit_auction_id'], unique=False)
    op.create_index(op.f('ix_chit_winner_payouts_chit_group_id'), 'chit_winner_payouts', ['chit_group_id'], unique=False)
    op.create_index(op.f('ix_chit_winner_payouts_client_request_id'), 'chit_winner_payouts', ['client_request_id'], unique=False)
    op.create_index(op.f('ix_chit_winner_payouts_organizer_id'), 'chit_winner_payouts', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_chit_winner_payouts_status'), 'chit_winner_payouts', ['status'], unique=False)
    op.create_index(op.f('ix_chit_winner_payouts_winner_member_id'), 'chit_winner_payouts', ['winner_member_id'], unique=False)
    op.create_index(op.f('ix_chit_winner_payouts_winner_membership_id'), 'chit_winner_payouts', ['winner_membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chit_winner_payouts_winner_membership_id'), table_name='chit_winner_payouts')
    op.drop_index(op.f('ix_chit_winner_payouts_winner_member_id'), table_name='chit_winner_payouts')
    op.drop_index(op.f('ix_chit_winner_payouts_status'), table_name='chit_winner_payouts')
    op.drop_index(op.f('ix_chit_winner_payouts_organizer_id'), table_name='chit_winner_payouts')
    op.drop_index(op.f('ix_chit_winner_payouts_client_request_id'), table_name='chit_winner_payouts')
    op.drop_index(op.f('ix_chit_winner_payouts_chit_group_id'), table_name='chit_winner_payouts')
    op.drop_index(op.f('ix_chit_winner_payouts_chit_auction_id'), table_name='chit_winner_payouts')
    op.drop_index('idx_winner_payouts_client_request_id', table_name='chit_winner_payouts', postgresql_where='client_request_id IS NOT NULL')
    op.drop_table('chit_winner_payouts')
    op.drop_index(op.f('ix_chit_month_financial_closures_organizer_id'), table_name='chit_month_financial_closures')
    op.drop_index(op.f('ix_chit_month_financial_closures_closure_status'), table_name='chit_month_financial_closures')
    op.drop_index(op.f('ix_chit_month_financial_closures_chit_group_id'), table_name='chit_month_financial_closures')
    op.drop_index(op.f('ix_chit_month_financial_closures_chit_auction_id'), table_name='chit_month_financial_closures')
    op.drop_table('chit_month_financial_closures')
    # ### end Alembic commands ###
